In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix , accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.kernel_approximation import RBFSampler
from sklearn.model_selection import GridSearchCV


import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Read dataset

In [2]:
df = pd.read_csv('villas.csv')

# EDA

In [3]:
# to print all dataset's column
pd.options.display.max_columns = 32

In [4]:
df.tail()

,Unnamed: 0.1,Unnamed: 0,front,bedrooms,livingrooms,bathrooms,streetWidth,stair,propertyAge,driverRoom,tent,patio,kitchen,outdoorRoom,garage,duplex,squareSpace,adNumber,lastUpdate,adViews,details,price,location,numberOfApartments,maidRoom,elevator,dimentions,furnished,scheme,pool,basement
51840,51840,4716,جنوبية,5,2,5+,20.0,1.0,0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,385,3547226,قبل يوم,"1,564",فيلا للبيع في حي المونسية ، الرياض ، الرياض,"2,250,000",شرق الرياض,1,1.0,1.0,385م طول - 1م عرض,NaN,NaN,NaN,NaN
51841,51841,4717,غربية,7+,2,5+,12.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,500,4391251,قبل 3 أيام,728,فيلا للبيع في شارع بدائع المرير ، حي ظهرة البد...,"1,050,000",غرب الرياض,NaN,1.0,NaN,25م طول - 20م عرض,NaN,NaN,NaN,NaN
51842,51842,4718,غربية,5,3,5+,20.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,200,3670119,قبل يوم,249,فيلا للبيع في شارع سدره ، حي طويق ، الرياض ، ا...,"1,000,000",غرب الرياض,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
51843,51843,4719,جنوبية غربية,1,NaN,1,15.0,NaN,0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,405,4448200,قبل 12 ساعة,40,فيلا للبيع في شارع اللوز ، حي النهضة ، الرياض ...,"2,300,000",شرق الرياض,2,NaN,NaN,20م طول - 20م عرض,NaN,NaN,NaN,NaN
51844,51844,4720,شمالية,6,2,5+,15.0,1.0,0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,750,4074453,قبل شهرين,355,فيلا للبيع في حي المونسية ، الرياض ، الرياض,"4,100,000",شرق الرياض,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# print dataset's rows and columns
rows, columns = df.shape
print(f'the dataset contains {rows} rows.')
print(f'the dataset contains {columns} columns.')

the dataset contains 51845 rows.
the dataset contains 31 columns.

In [6]:
# print dataset's details
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51845 entries, 0 to 51844
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0.1        51845 non-null  int64
 1   Unnamed: 0          51845 non-null  int64
 2   front               51845 non-null  object
 3   bedrooms            51845 non-null  object
 4   livingrooms         50614 non-null  object
 5   bathrooms           51845 non-null  object
 6   streetWidth         51640 non-null  float64
 7   stair               35387 non-null  float64
 8   propertyAge         45368 non-null  object
 9   driverRoom          18412 non-null  float64
 10  tent                23789 non-null  float64
 11  patio               39951 non-null  float64
 12  kitchen             50754 non-null  float64
 13  outdoorRoom         33178 non-null  float64
 14  garage              47031 non-null  float64
 15  duplex              15462 non-null  float64
 16  squareSpace         51845 non-null  object
 17  adNumber            51845 non-null  int64
 18  lastUpdate          51845 non-null  object
 19  adViews             51844 non-null  object
 20  details             51845 non-null  object
 21  price               51845 non-null  object
 22  location            51845 non-null  object
 23  numberOfApartments  21857 non-null  object
 24  maidRoom            39660 non-null  float64
 25  elevator            12424 non-null  float64
 26  dimentions          10807 non-null  object
 27  furnished           4062 non-null   float64
 28  scheme              2548 non-null   object
 29  pool                5832 non-null   float64
 30  basement            1938 non-null   float64
dtypes: float64(14), int64(3), object(14)
memory usage: 12.3+ MB

## Data Cleaning

In [7]:
# Note: Most of the data cleaning steps were applied using Excel.

In [8]:
# drop unnecessary columns
df.drop(['Unnamed: 0.1', 'Unnamed: 0','details', 'dimentions',
         'adViews', 'adNumber', 'lastUpdate', 'scheme'], inplace = True, axis = 1)

In [9]:
# print null values
df.isnull().sum()

front                     0
bedrooms                  0
livingrooms            1231
bathrooms                 0
streetWidth             205
stair                 16458
propertyAge            6477
driverRoom            33433
tent                  28056
patio                 11894
kitchen                1091
outdoorRoom           18667
garage                 4814
duplex                36383
squareSpace               0
price                     0
location                  0
numberOfApartments    29988
maidRoom              12185
elevator              39421
furnished             47783
pool                  46013
basement              49907
dtype: int64

In [10]:
# replace NaN with zeros
df['maidRoom'] = df['maidRoom'].replace(np.nan, 0)
df['furnished'] = df['furnished'].replace(np.nan, 0)
df['elevator'] = df['elevator'].replace(np.nan, 0)
df['pool'] = df['pool'].replace(np.nan, 0)
df['basement'] = df['basement'].replace(np.nan, 0)
df['numberOfApartments'] = df['numberOfApartments'].replace(np.nan, 0)
df['duplex'] = df['duplex'].replace(np.nan, 0)
df['garage'] = df['garage'].replace(np.nan, 0)
df['outdoorRoom'] = df['outdoorRoom'].replace(np.nan, 0)
df['kitchen'] = df['kitchen'].replace(np.nan, 0)
df['patio'] = df['patio'].replace(np.nan, 0)
df['driverRoom'] = df['driverRoom'].replace(np.nan, 0)
df['tent'] = df['tent'].replace(np.nan, 0)
df['stair'] = df['stair'].replace(np.nan, 0)

In [11]:
# print null values after filling some columns
df.isnull().sum()

front                    0
bedrooms                 0
livingrooms           1231
bathrooms                0
streetWidth            205
stair                    0
propertyAge           6477
driverRoom               0
tent                     0
patio                    0
kitchen                  0
outdoorRoom              0
garage                   0
duplex                   0
squareSpace              0
price                    0
location                 0
numberOfApartments       0
maidRoom                 0
elevator                 0
furnished                0
pool                     0
basement                 0
dtype: int64

In [12]:
# drop null values
df.dropna(inplace=True)

In [13]:
# print number of duplicated rows
df.duplicated().sum()

14804

In [14]:
# drop duplicated rows
df.drop_duplicates(inplace= True)

In [15]:
# applied data manupilating on price column
df['price'] = df['price'].replace(',','',regex=True)
df['price'] = pd.to_numeric(df['price'])

In [16]:
# applied data manupilating on squareSpace column
df['squareSpace'] = df['squareSpace'].replace(',','',regex=True)
df['squareSpace'] = pd.to_numeric(df['squareSpace'])

In [17]:
# change streetWidth data type
df['streetWidth'] = pd.to_numeric(df['streetWidth'])

In [18]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).sum()

basement              1185
bathrooms                0
bedrooms                 0
driverRoom               0
duplex                   0
elevator              7093
front                    0
furnished             2425
garage                2358
kitchen                548
livingrooms              0
location                 0
maidRoom              6635
numberOfApartments       0
outdoorRoom              0
patio                 6443
pool                  3402
price                 2052
propertyAge              0
squareSpace           2640
stair                    0
streetWidth           1016
tent                     0
dtype: int64

In [19]:
# print dataset's rows and columns after cleaning stage
rows, columns = df.shape
print(f'the dataset contains {rows} rows.')
print(f'the dataset contains {columns} columns.')

the dataset contains 29557 rows.
the dataset contains 23 columns.

## Data Visualization

# Machine Learning Algorithms

## Prepare data for ML

In [20]:
# the only solution to solve encoder error
df = df.astype({"bathrooms": str})
df = df.astype({"front": str})
df = df.astype({"livingrooms": str})
df = df.astype({"bathrooms": str})
df = df.astype({"propertyAge": str})
df = df.astype({"location": str})
df = df.astype({"numberOfApartments": str})

In [21]:
from sklearn import preprocessing
# select all categorical variables
df_categorical = df.select_dtypes(include=['object'])
df_categorical.head()

,front,bedrooms,livingrooms,bathrooms,propertyAge,location,numberOfApartments
0,شرقية,5,4,5+,0,جنوب الرياض,0
1,غربية,4,3,5+,0,غرب الرياض,2
2,جنوبية شرقية,7+,2,5+,31,جنوب الرياض,0
3,غربية,7+,3,5+,3,غرب الرياض,0
4,شمالية,4,2,4,0,شرق الرياض,3

In [22]:
# apply Label encoder to df_categorical
le = preprocessing.LabelEncoder()
df_categorical = df_categorical.apply(le.fit_transform)
df_categorical.head()

,front,bedrooms,livingrooms,bathrooms,propertyAge,location,numberOfApartments
0,5,4,3,4,0,0,0
1,9,3,2,4,0,3,9
2,3,6,1,4,25,0,0
3,9,6,2,4,23,3,0
4,6,3,1,3,0,1,12

In [23]:
# concat df_categorical with original df
df = df.drop(df_categorical.columns, axis=1)
df = pd.concat([df, df_categorical], axis=1)
df.head()

,streetWidth,stair,driverRoom,tent,patio,kitchen,outdoorRoom,garage,duplex,squareSpace,price,maidRoom,elevator,furnished,pool,basement,front,bedrooms,livingrooms,bathrooms,propertyAge,location,numberOfApartments
0,20.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,300,1050000,0.0,0.0,0.0,0.0,0.0,5,4,3,4,0,0,0
1,20.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,540,3000000,1.0,1.0,0.0,0.0,0.0,9,3,2,4,0,3,9
2,15.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,875,2000000,1.0,0.0,0.0,0.0,0.0,3,6,1,4,25,0,0
3,15.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,200,894000,1.0,0.0,1.0,0.0,0.0,9,6,2,4,23,3,0
4,25.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,400,3500000,1.0,1.0,1.0,0.0,0.0,6,3,1,3,0,1,12

# ML models

### Split dataset into training and testing

In [24]:
x = df.drop(['price'],axis=1)
y = df['price']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [26]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

#### SVM Model

In [27]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [28]:
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
grid.fit(x_train, y_train)
grid_predictions = grid.predict(x_test)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.032 total time= 3.0min
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.032 total time= 7.1min
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.032 total time= 6.1min
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.032 total time= 2.9min
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.032 total time= 3.0min
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.067 total time= 1.7min
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.070 total time=15.6min
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.068 total time= 1.7min
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.067 total time= 1.7min
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.071 total time=14.8min
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.065 total time= 1.3min
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.071 total time= 1.3min
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.062 total time= 1.3min
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.068 total time= 1.3min
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.066 total time= 1.3min
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.031 total time=18.6min
[CV 4/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 1/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.2min
[CV 2/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.2min
[CV 3/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.031 total time= 1.2min
[CV 4/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.2min
[CV 5/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.2min
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.056 total time= 3.7min
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.056 total time= 3.6min
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.067 total time= 3.6min
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.055 total time= 3.6min
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.057 total time= 3.6min
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.112 total time= 1.8min
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.100 total time= 1.8min
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.105 total time= 1.8min
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.101 total time= 1.8min
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.097 total time= 1.8min
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.089 total time= 1.3min
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.086 total time= 1.3min
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.083 total time= 1.3min
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.088 total time= 1.3min
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.082 total time= 1.3min
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.069 total time= 1.3min
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.074 total time= 1.3min
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.063 total time= 1.3min
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.073 total time= 1.3min
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.069 total time= 1.3min
[CV 1/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 2/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 3/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.031 total time= 1.3min
[CV 4/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 5/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.032 total time= 1.3min
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.058 total time= 3.7min
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.058 total time=66.4min
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.065 total time=21.1min
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.062 total time= 3.7min
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.056 total time= 3.7min
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.101 total time= 1.9min
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.093 total time= 1.9min
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.100 total time= 1.9min
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.105 total time= 1.9min
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.102 total time= 1.9min
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.113 total time= 1.3min
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.108 total time= 1.3min
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.117 total time= 1.3min
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.111 total time= 1.3min
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.109 total time= 1.3min
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.085 total time= 1.3min
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.085 total time= 1.3min
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.086 total time= 1.3min
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.085 total time= 1.3min
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.080 total time= 1.3min
[CV 1/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.069 total time= 1.3min
[CV 2/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.076 total time= 1.3min
[CV 3/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.064 total time= 1.3min
[CV 4/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.074 total time= 1.3min
[CV 5/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.069 total time= 1.3min
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.058 total time= 3.7min
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.058 total time= 3.6min
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.063 total time= 3.7min
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.058 total time= 3.7min
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.056 total time= 3.7min
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.089 total time= 1.9min
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.085 total time=19.4min
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.091 total time= 1.9min
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.096 total time= 1.9min
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.090 total time= 1.9min
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.125 total time= 1.4min
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.122 total time= 1.4min
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.116 total time= 1.4min
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.118 total time= 1.4min
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.117 total time= 1.4min
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.097 total time= 1.3min
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.099 total time= 1.3min
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.101 total time= 1.3min
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.097 total time= 1.3min
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.097 total time= 1.3min
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.084 total time= 1.3min
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.085 total time= 1.3min
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.085 total time= 1.3min
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.083 total time= 1.3min
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.079 total time= 1.3min
[CV 1/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.057 total time= 3.7min

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.058 total time= 3.6min
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.063 total time= 3.7min
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.058 total time= 3.7min
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.056 total time= 3.7min
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.090 total time= 1.9min
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.080 total time= 1.9min
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.084 total time= 1.9min
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.093 total time= 1.9min
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.089 total time= 1.9min
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.115 total time= 1.7min
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.112 total time= 1.7min
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.111 total time= 1.7min
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.111 total time=17.7min
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.106 total time= 1.7min
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.117 total time= 1.5min
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.114 total time= 1.5min
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.114 total time= 1.5min
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.106 total time= 1.5min
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.108 total time= 1.5min
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.095 total time= 1.4min
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.096 total time= 1.4min
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.098 total time= 1.4min
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.095 total time= 1.4min
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.092 total time= 1.4min

In [39]:
print(grid.best_params_)

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [40]:
print(grid.best_estimator_)

SVC(C=100, gamma=0.01)

In [29]:
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
         790       0.00      0.00      0.00         0
        1080       0.00      0.00      0.00         0
       70000       0.00      0.00      0.00         1
       90000       0.00      0.00      0.00         0
      100000       0.00      0.00      0.00         2
      108000       0.00      0.00      0.00         1
      113000       0.00      0.00      0.00         0
      130000       0.00      0.00      0.00         1
      150000       0.50      0.50      0.50         2
      165000       0.00      0.00      0.00         1
      170000       0.00      0.00      0.00         1
      180000       0.00      0.00      0.00         1
      250000       0.00      0.00      0.00         0
      300000       0.00      0.00      0.00         1
      320000       0.00      0.00      0.00         0
      350000       0.00      0.00      0.00         2
      450000       0.00      0.00      0.00         1
      490000       0.00      0.00      0.00         1
      500000       0.00      0.00      0.00         4
      535000       0.00      0.00      0.00         1
      550000       0.00      0.00      0.00         3
      560000       0.00      0.00      0.00         2
      570000       0.00      0.00      0.00         1
      580000       0.33      1.00      0.50         1
      590000       0.00      0.00      0.00         1
      595000       0.00      0.00      0.00         0
      600000       0.00      0.00      0.00         3
      605000       0.00      0.00      0.00         1
      620000       0.14      0.12      0.13        17
      630000       0.00      0.00      0.00         0
      640000       0.00      0.00      0.00         0
      645000       0.00      0.00      0.00         0
      650000       0.19      0.19      0.19        16
      660000       0.00      0.00      0.00         3
      670000       0.08      0.14      0.11         7
      680000       0.07      0.10      0.08        10
      690000       0.00      0.00      0.00         6
      695000       0.00      0.00      0.00         0
      700000       0.11      0.13      0.12        15
      710000       0.00      0.00      0.00         1
      719000       0.50      1.00      0.67         1
      720000       0.07      0.09      0.08        11
      730000       0.00      0.00      0.00         5
      750000       0.13      0.12      0.12        34
      760000       0.00      0.00      0.00         2
      770000       0.00      0.00      0.00         4
      775000       0.00      0.00      0.00         1
      780000       0.00      0.00      0.00         9
      790000       0.00      0.00      0.00         2
      795000       0.00      0.00      0.00         0
      800000       0.07      0.04      0.05        25
      810000       0.00      0.00      0.00         9
      815000       0.00      0.00      0.00         1
      820000       0.05      0.05      0.05        21
      822000       0.00      0.00      0.00         0
      825000       0.00      0.00      0.00         1
      830000       0.00      0.00      0.00        14
      832000       0.00      0.00      0.00         1
      835000       0.00      0.00      0.00         0
      840000       0.00      0.00      0.00        10
      845000       0.00      0.00      0.00         1
      849000       0.00      0.00      0.00         2
      849199       0.00      0.00      0.00         1
      850000       0.18      0.38      0.24        65
      855000       0.00      0.00      0.00         1
      860000       0.00      0.00      0.00        10
      870000       0.00      0.00      0.00        11
      880000       0.00      0.00      0.00        24
      890000       0.00      0.00      0.00         4
      895000       0.00      0.00      0.00         3
      895715       0.00      0.00      0.00         1
      900000       0.03      0.04      0.03        56
      905000       0.00      0.00      0.00         2
      910000       0.00      0.00      0.00         4
      920000       0.14      0.05      0.07        44
      930000       0.25      0.04      0.07        26
      940000       0.00      0.00      0.00        11
      950000       0.10      0.12      0.11       110
      960000       0.00      0.00      0.00        16
      965000       0.00      0.00      0.00         1
      970000       0.00      0.00      0.00        31
      975000       0.00      0.00      0.00         1
      980000       0.00      0.00      0.00        70
      990000       0.17      0.06      0.09        16
      999000       0.00      0.00      0.00         0
     1000000       0.10      0.07      0.08       138
     1000001       0.00      0.00      0.00         1
     1000070       0.00      0.00      0.00         1
     1000100       0.00      0.00      0.00         1
     1005000       0.00      0.00      0.00         1
     1010000       0.00      0.00      0.00         2
     1020000       0.00      0.00      0.00        21
     1030000       0.00      0.00      0.00        25
     1035000       0.00      0.00      0.00         0
     1040000       0.00      0.00      0.00         1
     1045000       0.00      0.00      0.00         1
     1050000       0.10      0.21      0.14       166
     1060000       0.19      0.14      0.16        22
     1065000       0.00      0.00      0.00         4
     1070000       0.26      0.15      0.19        39
     1071000       0.00      0.00      0.00         2
     1075000       0.00      0.00      0.00         3
     1080000       0.00      0.00      0.00        33
     1090000       0.76      0.52      0.62        25
     1095000       0.00      0.00      0.00         3
     1096000       0.00      0.00      0.00         2
     1097000       0.00      0.00      0.00         1
     1098000       0.24      0.67      0.35         6
     1099000       0.00      0.00      0.00         7
     1100000       0.16      0.31      0.21       232
     1101000       0.00      0.00      0.00         1
     1110000       0.00      0.00      0.00         0
     1120000       0.00      0.00      0.00        19
     1130000       0.00      0.00      0.00        37
     1135000       0.00      0.00      0.00         1
     1140000       0.00      0.00      0.00        13
     1145000       0.00      0.00      0.00         2
     1150000       0.16      0.19      0.18       179
     1151000       0.00      0.00      0.00         1
     1160000       0.00      0.00      0.00        14
     1164000       0.00      0.00      0.00         0
     1170000       0.18      0.04      0.06        55
     1175000       0.00      0.00      0.00         3
     1180000       0.00      0.00      0.00        40
     1185000       0.00      0.00      0.00         1
     1190000       0.00      0.00      0.00         1
     1200000       0.18      0.31      0.22       242
     1201000       0.00      0.00      0.00         1
     1210000       0.00      0.00      0.00         0
     1215000       0.00      0.00      0.00         1
     1218000       0.00      0.00      0.00         0
     1220000       0.00      0.00      0.00        12
     1225000       0.00      0.00      0.00         1
     1230000       0.00      0.00      0.00        27
     1231000       0.00      0.00      0.00         1
     1240000       0.00      0.00      0.00         5
     1249000       0.00      0.00      0.00         1
     1250000       0.15      0.22      0.18       161
     1260000       0.00      0.00      0.00         1
     1270000       0.00      0.00      0.00        26
     1280000       0.07      0.08      0.07        26
     1282500       0.00      0.00      0.00         1
     1290000       0.00      0.00      0.00         0
     1300000       0.08      0.12      0.09       191
     1300008       0.00      0.00      0.00         0
     1301000       0.00      0.00      0.00         1
     1310000       0.00      0.00      0.00         3
     1320000       0.00      0.00      0.00         7
     1325000       0.00      0.00      0.00         2
     1330000       0.10      0.05      0.06        22
     1340000       0.00      0.00      0.00         2
     1350000       0.06      0.04      0.05       129
     1356000       0.00      0.00      0.00         0
     1360000       0.00      0.00      0.00         7
     1370000       0.50      0.04      0.07        26
     1380000       0.00      0.00      0.00        17
     1385000       0.00      0.00      0.00         0
     1390000       0.00      0.00      0.00         0
     1399000       0.00      0.00      0.00         1
     1400000       0.08      0.12      0.10       193
     1420000       0.00      0.00      0.00         7
     1430000       0.00      0.00      0.00         6
     1450000       0.11      0.07      0.08       114
     1450002       0.00      0.00      0.00         1
     1460000       0.00      0.00      0.00         2
     1470000       0.00      0.00      0.00         8
     1480000       0.00      0.00      0.00        16
     1490000       0.00      0.00      0.00         3
     1500000       0.07      0.08      0.07       204
     1500002       0.00      0.00      0.00         1
     1500007       0.00      0.00      0.00         1
     1500009       0.00      0.00      0.00         1
     1502000       0.00      0.00      0.00         1
     1520000       0.00      0.00      0.00         4
     1530000       0.00      0.00      0.00         4
     1540000       0.00      0.00      0.00         1
     1550000       0.10      0.06      0.07       108
     1550002       0.00      0.00      0.00         1
     1560000       0.00      0.00      0.00         9
     1570000       0.00      0.00      0.00         5
     1574000       0.00      0.00      0.00         0
     1580000       0.00      0.00      0.00         1
     1590000       0.00      0.00      0.00         0
     1599000       0.00      0.00      0.00         1
     1600000       0.15      0.26      0.19       218
     1600002       0.00      0.00      0.00         0
     1620000       0.00      0.00      0.00         2
     1630000       0.00      0.00      0.00         5
     1650000       0.11      0.04      0.06       145
     1650001       0.00      0.00      0.00         0
     1670000       0.00      0.00      0.00         2
     1680000       0.00      0.00      0.00         3
     1690000       0.00      0.00      0.00         1
     1700000       0.05      0.03      0.04       107
     1700002       0.00      0.00      0.00         1
     1725000       0.00      0.00      0.00         1
     1730000       0.00      0.00      0.00         1
     1750000       0.14      0.07      0.09        61
     1750002       0.00      0.00      0.00         1
     1760000       0.00      0.00      0.00         1
     1770000       0.00      0.00      0.00         1
     1775000       0.00      0.00      0.00         1
     1780000       0.00      0.00      0.00         1
     1800000       0.08      0.06      0.07       112
     1800002       0.00      0.00      0.00         0
     1800050       0.00      0.00      0.00         0
     1820000       0.00      0.00      0.00         1
     1840000       0.00      0.00      0.00         3
     1850000       0.12      0.09      0.11        85
     1860000       0.00      0.00      0.00         3
     1870000       0.00      0.00      0.00         1
     1880000       0.00      0.00      0.00         4
     1890000       0.00      0.00      0.00         2
     1900000       0.07      0.07      0.07       105
     1900002       0.00      0.00      0.00         1
     1925000       0.00      0.00      0.00         1
     1930000       0.00      0.00      0.00         1
     1950000       0.00      0.00      0.00        56
     1950002       0.00      0.00      0.00         1
     1950010       0.00      0.00      0.00         1
     1980000       0.00      0.00      0.00         1
     1990000       0.00      0.00      0.00         0
     2000000       0.12      0.18      0.14       181
     2000006       0.00      0.00      0.00         1
     2000100       0.00      0.00      0.00         1
     2000200       0.00      0.00      0.00         1
     2000250       0.00      0.00      0.00         0
     2050000       0.00      0.00      0.00        19
     2060000       0.00      0.00      0.00         1
     2060010       0.00      0.00      0.00         1
     2080000       0.00      0.00      0.00         0
     2100000       0.06      0.06      0.06       112
     2100001       0.00      0.00      0.00         1
     2100002       0.00      0.00      0.00         0
     2100020       0.00      0.00      0.00         0
     2100090       0.00      0.00      0.00         0
     2120000       0.00      0.00      0.00         1
     2145000       0.00      0.00      0.00         0
     2150000       0.00      0.00      0.00        26
     2190000       0.00      0.00      0.00         2
     2200000       0.15      0.24      0.19       176
     2200002       0.00      0.00      0.00         1
     2200003       0.00      0.00      0.00         1
     2225000       0.00      0.00      0.00         1
     2249000       0.00      0.00      0.00         0
     2250000       0.20      0.09      0.12        69
     2270000       0.00      0.00      0.00         1
     2275000       0.00      0.00      0.00         1
     2280000       0.00      0.00      0.00         2
     2300000       0.13      0.11      0.12       122
     2300001       0.00      0.00      0.00         0
     2300002       0.00      0.00      0.00         0
     2300003       0.00      0.00      0.00         1
     2350000       0.00      0.00      0.00        24
     2350001       0.00      0.00      0.00         0
     2360000       0.00      0.00      0.00         1
     2370000       0.00      0.00      0.00         0
     2375000       0.33      0.33      0.33         3
     2380000       0.00      0.00      0.00         0
     2390000       0.00      0.00      0.00         1
     2400000       0.12      0.11      0.11        85
     2409000       0.00      0.00      0.00         1
     2430000       0.00      0.00      0.00         3
     2450000       0.00      0.00      0.00        20
     2480000       0.00      0.00      0.00         0
     2500000       0.10      0.14      0.12       181
     2520000       0.00      0.00      0.00         1
     2550000       0.20      0.11      0.14        46
     2560000       0.00      0.00      0.00         1
     2580000       0.00      0.00      0.00         0
     2600000       0.11      0.08      0.09        75
     2610000       0.00      0.00      0.00         1
     2648500       0.00      0.00      0.00         1
     2649000       0.00      0.00      0.00         1
     2650000       0.00      0.00      0.00        19
     2700000       0.20      0.10      0.13        80
     2750000       0.00      0.00      0.00        11
     2770000       0.00      0.00      0.00         1
     2800000       0.11      0.13      0.12       104
     2845000       0.00      0.00      0.00         0
     2850000       0.20      0.07      0.11        41
     2875000       0.00      0.00      0.00         0
     2890000       0.00      0.00      0.00         1
     2900000       0.11      0.07      0.08        44
     2950000       0.00      0.00      0.00        12
     2950555       0.00      0.00      0.00         1
     2980000       0.00      0.00      0.00         0
     2999999       0.00      0.00      0.00         1
     3000000       0.13      0.21      0.16       195
     3000300       0.00      0.00      0.00         1
     3050000       0.00      0.00      0.00         3
     3099000       0.00      0.00      0.00         1
     3100000       0.08      0.03      0.05        32
     3149000       0.00      0.00      0.00         1
     3150000       0.00      0.00      0.00         9
     3175000       0.00      0.00      0.00         1
     3200000       0.09      0.11      0.10        61
     3220000       0.00      0.00      0.00         0
     3249000       0.00      0.00      0.00         1
     3250000       0.00      0.00      0.00         9
     3300000       0.16      0.14      0.15        69
     3340000       0.00      0.00      0.00         1
     3350000       0.00      0.00      0.00        10
     3360000       0.00      0.00      0.00         1
     3380000       0.00      0.00      0.00         1
     3400000       0.03      0.03      0.03        32
     3437500       0.00      0.00      0.00         1
     3450000       0.00      0.00      0.00         4
     3500000       0.12      0.19      0.15       108
     3520000       0.00      0.00      0.00         1
     3550000       0.00      0.00      0.00         6
     3600000       0.00      0.00      0.00        34
     3650000       0.00      0.00      0.00         7
     3670000       0.00      0.00      0.00         1
     3676000       0.00      0.00      0.00         1
     3700000       0.22      0.04      0.07        45
     3750000       0.00      0.00      0.00         4
     3800000       0.14      0.03      0.05        33
     3850000       0.00      0.00      0.00         2
     3900000       0.12      0.10      0.11        21
     3950000       0.00      0.00      0.00         1
     3970000       0.00      0.00      0.00         0
     3980000       0.00      0.00      0.00         1
     3990000       0.00      0.00      0.00         0
     3999000       0.00      0.00      0.00         1
     4000000       0.10      0.11      0.11        79
     4050000       0.00      0.00      0.00         0
     4060000       0.00      0.00      0.00         1
     4100000       0.29      0.13      0.18        15
     4150000       0.00      0.00      0.00         4
     4200000       0.14      0.14      0.14        36
     4250000       0.33      0.17      0.22         6
     4300000       0.07      0.07      0.07        30
     4350000       0.00      0.00      0.00         7
     4400000       0.33      0.05      0.09        19
     4446000       0.00      0.00      0.00         0
     4450000       0.00      0.00      0.00         1
     4500000       0.16      0.17      0.16        90
     4500009       0.00      0.00      0.00         0
     4550000       0.00      0.00      0.00         1
     4600000       0.00      0.00      0.00         5
     4650000       0.00      0.00      0.00         1
     4700000       0.17      0.08      0.11        24
     4750000       0.00      0.00      0.00         1
     4800000       0.00      0.00      0.00         9
     4850000       0.00      0.00      0.00         3
     4875000       0.00      0.00      0.00         0
     4900000       0.50      0.14      0.22         7
     4950000       0.00      0.00      0.00         0
     5000000       0.17      0.22      0.20        63
     5000200       0.00      0.00      0.00         1
     5040000       0.00      0.00      0.00         1
     5050000       0.00      0.00      0.00         0
     5100000       0.00      0.00      0.00         4
     5150000       0.00      0.00      0.00         5
     5200000       0.23      0.21      0.22        14
     5250000       0.00      0.00      0.00         1
     5300000       0.00      0.00      0.00         7
     5340000       0.00      0.00      0.00         1
     5400000       0.00      0.00      0.00         2
     5450000       0.00      0.00      0.00         2
     5500000       0.07      0.10      0.08        21
     5550000       0.00      0.00      0.00         1
     5600000       0.00      0.00      0.00         4
     5650000       0.00      0.00      0.00         7
     5700000       0.17      0.08      0.11        13
     5800000       0.23      0.30      0.26        10
     5850000       0.00      0.00      0.00         1

In [41]:
svm = SVC(C=100, gamma=0.01, kernel='rbf')
svm.fit(x_train,y_train)
svm_pred = svm.predict(x_test)

In [42]:
print('SVM Model Accuracy :',accuracy_score(svm_pred,y_test)) 
print('Accuracy on training set:',svm.score(x_train,y_train))
print('Accuracy on test set:',svm.score(x_test,y_test))

SVM Model Accuracy : 0.1205683355886333
Accuracy on training set: 0.47791762529886767
Accuracy on test set: 0.1205683355886333

In [43]:
scores = cross_val_score(svm, x, y, cv=10)
print("Accuracy: {:.1f} %".format(scores.mean()*100))

Accuracy: 23.0 %

#### KNN Model

In [33]:
knn = KNeighborsClassifier(weights = 'distance', n_neighbors = 7)
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)

In [34]:
print('KNN Model Accuracy :',accuracy_score(knn_pred,y_test)) 
print('Accuracy on training set:',knn.score(x_train,y_train))
print('Accuracy on test set:',knn.score(x_test,y_test))

KNN Model Accuracy : 0.07794316644113668
Accuracy on training set: 0.9644967744845943
Accuracy on test set: 0.07794316644113668

In [35]:
scores = cross_val_score(knn, x, y, cv=10)
print("Accuracy: {:.1f} %".format(scores.mean()*100))

Accuracy: 22.0 %

#### Decision Tree Model

In [36]:
ds = DecisionTreeClassifier()
ds.fit(x_train,y_train)
ds_prediction =  ds.predict(x_test)

In [37]:
print('Ds Model Accuracy :',accuracy_score(ds_prediction,y_test)) 
print('Accuracy on training set:',ds.score(x_train,y_train))
print('Accuracy on test set:',ds.score(x_test,y_test))

Ds Model Accuracy : 0.17550744248985115
Accuracy on training set: 0.9644967744845943
Accuracy on test set: 0.17550744248985115

In [44]:
scores = cross_val_score(ds, x, y, cv=10)
print("Accuracy: {:.1f} %".format(scores.mean()*100))

Accuracy: 18.6 %